### ISSUE TITLE
Regarding hardcoded uuids in the Cyclic Operation Causes OperationKey Updates 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#129]
@MartinSunal , I was going through the code of OKM and noticed that there are two files , where we are hardcoding the uuids, 
server/utils/ltpClientConstants.js
server/utils/ltpServerConstants.js

In both the files we have multiple entries , But , in the code I could able to see that only few of them are utilized (in the /server/service/IndividualServicesService.js), 

**server/utils/ltpClientConstants.js** 
1.	HTTP_NEW_RELEASE   in the bequeath-your-data-and-die logic to update the release number of New release
**Solution :** By using the forwardingName PromptForBequeathingDataCausesTransferOfListOfApplications , new release ltp instance shall be traced.
2.	HTTP_ALT_OPERATION_LIST_LINK_UUIDS('okm-0-0-1-op-c-3072')   to fetch LinkUuidList From Alt
HTTP_ALT_OPERATION_LIST_ENDPOINTS_OF_LINK('okm-0-0-1-op-c-3073')  to fetch LinkEndpointList From ALT
**Solution :** 
The hardcoded values are part of the CyclicOperationCausesOperationKeyUpdates forwarding. 
	Instead of hardcoding the uuids , shall we consider the first two output fc port to get details from the ALT sequence considered as per the ascending order of the local-id.
	Or
	shall we ask for two separate invariant forwarding , 1 for getting the list of links and other for getting the list of end points of link.

**server/utils/ltpServerConstants.js**
1.	HTTP_THIS_OPERATION_INFORM_ABOUT_APPLICATION_IN_GENERIC_REPRESENTATION  To include the consequent action in the start-application-in-generic-representation
**Solution :** This shall be resolved as per new Generic representation concept with action-profile.

### Next Steps
Kindly please let me know your views regarding the following , 
1. Apart from the above mentioned 4 instances , if other instances are not used anywhere shall this be removed from the code? 
2. Solution provided to overcome using the hardcoded uuid values are fine or will it cause any problem ? If not , shall we remove the two constant files from the utils directory ?

**Comment by PrathibaJee** [comment]
Please refer the [comment ](https://github.com/openBackhaul/OperationKeyManagement/issues/6#issuecomment-1356221780) in the [issue#6](https://github.com/openBackhaul/OperationKeyManagement/issues/6).
As per the decision , 
Former CyclicOperationCausesOperationKeyUpdates FC will be decomposed into FCs:
CyclicOperationCausesRequestForListOfLinks
CyclicOperationCausesRequestForLinkEndPoints
CyclicOperationCausesOperationKeyUpdates

Reference to the new forwardingConstructs shall be considered for performing CyclicOperationUpdate. And the hardcoded values shall be removed.

**Comment by vanithavalluripalli9** [comment]
Thee changes are pushed as part of pull request https://github.com/openBackhaul/OperationKeyManagement/pull/162
