### ISSUE TITLE
Include uuid syntax for the /v1/update-operation-key attribute for the service regard-application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#134]
As a part of regard-application , for the basic service “/v1/update-operation-key” a new operation-client will be created for the regarded application.
As per the specification , the reserved uuid syntax for this operationName is 
```
<own application abbreviation>-<release-number-of-own-separated-by-hypens>-op-c-is-<application abbreviation>-<release-number-separated-by-hypens>-000
```
Create a OperationClient if not available. Update the OperationClient configuration if the client is already available.

Also , currently this is “redirect-service-request-information” hardcoded in the serverside logic.

**Comment by vanithavalluripalli9** [comment]
This issue is fixed with changes in https://github.com/openBackhaul/OperationKeyManagement/pull/150
