### ISSUE TITLE
Support version 2.0.0 changes

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#140]
To completely implement the version 2.0.0 changes , the following tasks and their subtasks needs to be completed.
All the tasks needs to be implemented , tested , reviewed and merged to the develop branch.

### Individual Services : 
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/132
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/136
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/137
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/138
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/139
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/22
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/86

### Basic Services : 
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/146

### OAM Services : 
- [ ] https://github.com/openBackhaul/OperationKeyManagement/issues/147

**Comment by vanithavalluripalli9** [comment]
As all issues related are done , closing the issue
