### ISSUE TITLE
FileProfile not required

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/OperationKeyManagement#165]
As per understanding , file-profile contains the file details where we store application specific data.

In current Operation Key Management application , apart from Operation Modes we are not having any application specific data.

However , Operation Modes are stored in string profile . 

**Proposal :** 
Can we remove file profile from Operation Key Management as there is no application specific data we are storing in file.

**Changes required** (If above proposal is accepted) : 

1) To remove file profile related OAM Layer services from OAS of OKM application.
2) To remove file profile from config.json file of OKM application.

**Comment by openBackhaul** [comment]
Call on 17th of February:
Follow the proposal and delete the FileProfile from all specification components.

**Comment by openBackhaul** [comment]
Changed as proposed.
