### ISSUE TITLE
PromptForBequeathingDataCausesALTbeingRequestedToNotifyLinkUpdatesToNewRelease OUTPUT port-direction uuid from "okm-0-0-1-op-c-3071" to  "okm-0-0-1-op-c-3070"

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/OperationKeyManagement#20]
The PromptForBequeathingDataCausesALTbeingRequestedToNotifyLinkUpdatesToNewRelease is an invariant forwarding-construct.

This forwarding will help ALT to notify the link updates to the new release of OKM.

As of now , the OUTPUT Port-direction uuid is "okm-0-0-1-op-c-3071" . This uuid is for the service "/v1/end-subscription". So the intended redirection to new release will not happen.

The OUTPUT port-direction uuid should be "okm-0-0-1-op-c-3070" which corresponds to the service "/v1/notify-link-updates"

Proposal :

1. In the forwarding-construct PromptForBequeathingDataCausesALTbeingRequestedToNotifyLinkUpdatesToNewRelease

2. The OUTPUT port-direction uuid should be changed from "okm-0-0-1-op-c-3071" to  "okm-0-0-1-op-c-3070"

3. This will allow the ALT to notify the link updates  to the new release of OKM.

**Comment by openBackhaul** [comment]
OKM LOADfile line 2226 and OKM forwardingList line 104 have to be changed from "okm-0-0-1-op-c-3071" to "okm-0-0-1-op-c-3070" for referencing the /v1/notify-link-updates/.

**Comment by openBackhaul** [comment]
Already done.
