### ISSUE TITLE
Modify : /v1/update-operation-key request body to align to the published specification

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#22]
In the published specification of RO , TAR , AA, EaTL, OL , ALT and OKM ,  for the /v1/update-operation-key api , we have 3 required attributes including the "old-operation-key" . In OKM , the request body of the /v1/update-operation-key is not having the attribute "old-operation-key"(as per the decision and fix made in the [ApplicationPattern#issues#90](https://github.com/openBackhaul/ApplicationPattern/issues/90)) . This makes the service /v1/update-operation-key to fail setting the operation-key.

### Proposals : 
**proposal#1 :** 
Modifying the /v1/update-operation-key service request body in the operation-key-management to support the attribute "old-operation-key" with a dummy value. So that the service works fine for now.
**proposal#2 :** 
Manually manipulating the api/openapi.yaml in the server side code of RO , TAR , AA, EaTL, OL , ALT and OKM to remove the "old-operation-key" attribute from the request body of the service /v1/update-operation-key.

Incase if the proposal#2 is preferred over proposal#1, then please create separate issue in RO , TAR , AA, EaTL, OL , ALT and OKM to manually manipulate the api/openapi.yaml.

**Comment by vanithavalluripalli9** [comment]
This issues is fixed as part of basic services implementation and was working fine
