### ISSUE TITLE
Problem in updating the operation-key of OKM’s /v1/update-operation-key API’s server and client

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#258]
Updating operation-keys for the following endpoints creates a problem , 
```
Operation-name : /v1/update-operation-key
Serving uuid : okm-2-0-1-op-s-bm-010
Consuming uuid : okm-2-0-1-op-c-is-okm-2-0-1-000
```

**Initial configuration :**
Mode : Protection/reactive mode
OKM :
okm-2-0-1-op-s-bm-010 : /v1/update-operation-key : Operation key not yet provided
okm-2-0-1-op-c-is-okm-2-0-1-000: /v1/update-operation-key : Operation key not yet provided
         

1. **Step1 : OKM set the operation-key of okm-2-0-1-op-s-bm-010 to “123456789”**
            Request : 
            url and operation-key will be formulated from 
            okm-2-0-1-op-c-is-okm-2-0-1-000: /v1/update-operation-key : Operation key not yet provided
            requestBody :
            {
            Uuid : okm-2-0-1-op-s-bm-010 , new-operation-key : “123456789”
            }
            Consequence :
            OKM :
            okm-2-0-1-op-s-bm-010 : /v1/update-operation-key : “123456789”
            okm-2-0-1-op-c-is-okm-2-0-1-000: /v1/update-operation-key : Operation key not yet provided

2. **Step2 : OKM set the operation-key of okm-2-0-1-op-c-is-okm-2-0-1-000 to “123456789”**
            Request : 
            url and operation-key will be formulated from 
            okm-2-0-1-op-c-is-okm-2-0-1-000: /v1/update-operation-key : Operation key not yet provided
            requestBody :
            {
            Uuid : okm-2-0-1-op-c-is-okm-2-0-1-000, new-operation-key : “123456789”
            }
            Consequence :
            401 response code because the operation-key of the outdated operation-key
                

> Note :
> In the application , in order to avoid this problem for now , we gave a bad fix that , if there is an update in the server uuid(okm-2-0-1-op-s-bm-010) , the client uuid(okm-2-0-1-op-c-is-okm-2-0-1-000) will also be updated.

**Comment by openBackhaul** [comment]
![image](https://github.com/openBackhaul/OperationKeyManagement/assets/46722892/702caf7a-ce11-4064-a424-103ead77194a)

**Comment by IswaryaaS** [comment]
Closed as a new issue has been created https://github.com/openBackhaul/OperationKeyManagement/issues/265 for change in implementation
