### ISSUE TITLE
To include a rollback procedure if the /v1/regard-application is not successful

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#309]
After a new application is regarded to OKM,
OKM will , 
1. create tcp, http , operation client stack for the newly regarded application
2. create link for the "/v1/update-operation-key" API between the server(NewApp) and the client(OKM) in ALT
3. If the link created successfully , 
    then 
          **OKM** respond to **RO** that "successfully-connected : **true**"
    else
          **OKM** respond to **RO** that "successfully-connected : **false**" with reason for failure

**Problem:** 
If **OKM** holds the correct TCP/IP information of an application 
**AND** 
If **ALT** **dont** have a link for the **"/v1/update-operation-key" API** between the server(NewApp) and the client(OKM)
then , 
during the cyclic process in protection mode , 
the operation-key of the "/v1/update-operation-key" in the serving application will be changed.
**This will result in blocking OKM to access the "/v1/update-operation-key" API in the serving application.**

**Proposal :**
Shall we add the following procedure incase of a failure ?
If the link is created successfully , 
then 
OKM respond to RO that "successfully-connected : true"
else
**OKM shall delete the tcp, http , operation client stack for the newly regarded application (rollback)**
OKM respond to RO that "successfully-connected : false" with reason for failure

**Comment by openBackhaul** [comment]
Rollback has been implemented as self-calling OKM://v1/dispose-remainders-of-deregistered-application.
Rollback will be triggered by timeout of OKM://v1/update-operation-key.
