### ISSUE TITLE
Few Uuids shall be added to INPUT fc-port of ServiceRequestCausesLoggingRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#310]
In [forwardings.yaml](https://github.com/openBackhaul/OperationKeyManagement/blob/develop/spec/OperationKeyManagement%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/OperationKeyManagement/blob/develop/spec/OperationKeyManagement%2Bconfig.json), in INPUT fc-port of forwarding-construct ServiceRequestCausesLoggingRequest, we shall need to add the following services.

okm-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
okm-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
okm-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release

**Comment by openBackhaul** [comment]
Changed as proposed.
