### ISSUE TITLE
A small typo in LinkUpdateNotificationCausesOperationKeyUpdates shall be corrected. 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#313]
In [forwardings.yaml ](https://github.com/openBackhaul/OperationKeyManagement/blob/develop/spec/OperationKeyManagement%2Bforwardings.yaml) file, we have two operation-clients in initiating-requests. 
The second operation-client's server-name shall be updated to /v2/regard-application (server name for okm-2-1-0-op-s-is-005).

**Comment by openBackhaul** [comment]
Corrected as proposed.
