### ISSUE TITLE
Remove CurrentController occurrence from forwardings.yaml file

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#314]
As per decision made on [AP/#issue836](https://github.com/openBackhaul/ApplicationPattern/issues/836), instances of CurrentController shall be expected to be removed from specification files. 

In [forwardings.yaml](https://github.com/openBackhaul/OperationKeyManagement/blob/develop/spec/OperationKeyManagement%2Bforwardings.yaml) file, this shall be removed .

**Comment by openBackhaul** [comment]
Changed as proposed.
