### ISSUE TITLE
Load file : detailed-logging-is-on attribute to be removed from logical-termination-point instances

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#32]
As per understanding, detailed-logging-is-on attribute is applicable only for the operation "/v1/record-service-request" of ExecutionAndTraceLog

Problem Description:
In load-file, [OperationKeyManagement_0.0.2_tsi.220110.2010+data.2.json](https://github.com/openBackhaul/OperationKeyManagement/blob/develop/OperationKeyManagement_0.0.2_tsi.220110.2010%2Bdata.2.json),  for ltp instance okm-0-0-1-op-c-2040  contains an additional attribute _detailed-logging-is-on_, which needs to be removed.

Note : 
- okm-0-0-1-op-c-2040 refers to  /v1/update-operation-key

Related issues:
https://github.com/openBackhaul/ApplicationLayerTopology/issues/63
https://github.com/openBackhaul/AdministratorAdministration/issues/40
https://github.com/openBackhaul/OamLog/issues/41
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/47

**Comment by openBackhaul** [comment]
Already done.
