### ISSUE TITLE
To modify the profile-name of the profile instance okm-2-1-0-integer-p-000

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#323]
The profile-name of the profile instance okm-2-1-0-integer-p-000 is "integer-profile-1-0:PROFILE_NAME_INTEGER_PROFILE"
This needs to be modified to "integer-profile-1-0:PROFILE_NAME_**TYPE**_INTEGER_PROFILE"

> !Note : For other TAC applications this is modelled correctly.

**Comment by openBackhaul** [comment]
Covered by pull-request [#362](https://github.com/openBackhaul/OperationKeyManagement/pull/362)
