### ISSUE TITLE
response code PromptForBequeathingDataCausesTransferOfListOfApplications shall be udpated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#326]
- In OAS file, we have the callback PromptForBequeathingDataCausesTransferOfListOfApplications under /v1/bequeath-your-data-and-die. 
- This callback is targeted towards NewRelease://v1/regard-application. 
- The actual response code of /v1/regard-application has been updated to 200 from v2.1.1. 
- This change shall be incorporated to the response code of PromptForBequeathingDataCausesTransferOfListOfApplications which shall be "200" instead of 204

**Comment by openBackhaul** [comment]
ResponseCode changed to 200.
