### ISSUE TITLE
To remove subscription instead of sending /v1/dispose-remainders-of-deregistered-application is regard-application is not successful

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#334]
If OKM could not able to regard an application due to any internal failure , 
then 
as of now OKM will send /v1/dispose-remainders-of-deregistered-application
Reason : To ensure that OKM is not sending update-operation-keys to the regarded application's operation-server.
This is modelled so.

Problem : 
Incase if the regarded application is one of the TAC and OKM has invariant forwardings for this application.
Then disposal deletes the http-client resulting in non functioning of the invariant forwardings.

Proposal :
For all the application , if it is not regarded successfully , then instead of disposing that application , 
only the subscription will be deleted from the following forwardings, 
LinkUpdateNotificationCausesOperationKeyUpdates
CyclicOperationCausesOperationKeyUpdates

**Comment by IswaryaaS** [comment]
For implementing the proposal, the op-s uuid of /v1/regard-application (okm-2-1-0-op-s-bm-001) shall be added to ServiceRequestCausesFcPortDeletionRequest
