### ISSUE TITLE
server : unexpected termination of server during /v1/bequeath-your-data-and-die

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#34]
While triggering /v1/bequeath-your-data-and-die, a series of callbacks will be called to other applications for scenarios like transferring application specific data, creating/ending subscriptions. 
While the callbacks are being triggered from the application, we could observe an unexpected behavior.

Problem:
The server is abruptly stopped with an error message thrown after the callback request fails. 
Error message : 
>> ${forwarding} is not success for the input[object Object] node:internal/process/promises:246
		triggerUncaughtException(err, true /* fromPromise */);

Expected behavior:
When any callback request fails, /v1/bequeath-your-data-and-die should not proceed further for next callback. The application should  not stop abruptly and it runs normally.

Related issues:
https://github.com/openBackhaul/RegistryOffice/issues/96
https://github.com/openBackhaul/TypeApprovalRegister/issues/45
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/48
https://github.com/openBackhaul/OamLog/issues/43
https://github.com/openBackhaul/AdministratorAdministration/issues/42
https://github.com/openBackhaul/ApplicationLayerTopology/issues/69

**Comment by MartinSunal** [comment]
It's been already fixed as a part of PR https://github.com/openBackhaul/OperationKeyManagement/pull/35
