### ISSUE TITLE
Update response-body of /v1/regard-application

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#369]
For the service /v1/regard-application, the response-body contains two schemas.
Out of those two schemas , the second one's ((IF ( (NOT (200 OR 204)) OR (successfully-connected==false) OR (waiting>maximumWaitTimeToReceiveOperationKey) )' )) contains an attribute called "reason-of-failure" .

Out of the enumerations, the value OKM_NOT_REACHABLE has been updated to two values 'OKM_DID_NOT_REACH_ALT' and 'OKM_DID_NOT_REACH_NEW_APPLICATION'.

The above two values shall be formulated under following scenarios:

During callbacks of /v1/regard-application,

- when OKM tries to reach ALT and if ALT is down, then "OKM_DID_NOT_REACH_ALT" shall be formulated
- when OKM tries to reach the new regarding application and if the new application is down, then "OKM_DID_NOT_REACH_NEW_APPLICATION" shall be formulated in "reason-of-failure".

**Comment by PrathibaJee** [comment]
> Note : the second condition mentioned in this issue is not handled in the PR#https://github.com/openBackhaul/OperationKeyManagement/pull/372/files when OKM tries to reach the new regarding application and if the new application is down, then "OKM_DID_NOT_REACH_NEW_APPLICATION" shall be formulated in "reason-of-failure" condition

**Comment by ManasaBM1** [comment]
the second condition mentioned in above issue i.e. "OKM_DID_NOT_REACH_NEW_APPLICATION" is not applicable for the OKM Application
