### ISSUE TITLE
Support changes to v2.1.2_spec

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#370]
The following changes shall be made in OperationKeyManagement server side to support changes made in [v2.1.2_spec](https://github.com/openBackhaul/OperationKeyManagement/releases/tag/v2.1.2_spec)
 
- [x] https://github.com/openBackhaul/OperationKeyManagement/issues/368
- [x] https://github.com/openBackhaul/OperationKeyManagement/issues/369
- [x] Apart from individual service specific changes, the basic service operations shall be integrated and tested as per latest v2.1.2_spec of AP.

Bug fixing/Enhancement:
- [x] https://github.com/openBackhaul/OperationKeyManagement/issues/371

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
