### ISSUE TITLE
To remove response header parameter BackendTime for failed request

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#371]
As per https://github.com/openBackhaul/ApplicationPattern/issues/903. backendTime shall be removed from responseHeader of negative responses. 

To achieve the same, a minor change has been made in https://github.com/openBackhaul/ApplicationPattern/pull/1011. 

Additionally, in _Controllers/BasicServices.js and Controllers/IndividualServices.js_ file, "-1" shall be used in last placeholder in below line in **catch** block for all services

`let responseHeader = await RestResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, -1);`

![image](https://github.com/user-attachments/assets/00c00b00-c3e5-47c0-8b9b-9870f6ceb7d3)

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
