### ISSUE TITLE
Code optimization required in To handle response Code in the v1/regard-application service

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/OperationKeyManagement#375]
issue Description : Code optimization required in To handle response Code in the v1/regard-application service to handle the response code failures

**Comment by aleroldan156** [comment]
install this

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
