### ISSUE TITLE
Description of values of the StringProfile to be added

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/OperationKeyManagement#39]
A multi line description for explaining the respective meaning of the values  

- 'string-profile-1-0:STRING_VALUE_TYPE_REACTIVE' 
- 'string-profile-1-0:STRING_VALUE_TYPE_SANITATION'
- 'string-profile-1-0:STRING_VALUE_TYPE_PROTECTION'
- 'string-profile-1-0:STRING_VALUE_TYPE_OFF'  

of the enumeration at the PUT method of path  

_/core-model-1-4:control-construct/profile-collection/profile=okm-0-0-1-string-p-0000/string-profile-1-0:string-profile-pac/string-profile-configuration/string-value_

needs to be added.

**Required Changes to the OAS:**

- The value 'string-profile-1-0:STRING_VALUE_TYPE_SANITATION' shall be deleted from the modeling, since necessary data is no longer provided by the ApplicationLayerTopology application.  
 
- The following description shall be added to the PUT method for setting the value of the String:
```
description: >
  'reactive: a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link)
   protection: new values get periodically written into the operationKey attributes at servers and connected clients
   off: no automated changes to the values of the operationKey attributes at servers or clients
  '
```

**Comment by PrathibaJee** [comment]
1. When OperationKeyManagement(OKM) is operating in the reactive mode , once a link is approved by the ApplicationLayerTopology(ALT) , OKM updates the operation-key immediately to the approved client application.

2. When OKM is operating in the protection mode , once a link is approved by the ALT , OKM will not update the operation-key immediately. OKM updates the operation-key in its next cycle(max delay = 5 mins).
**Disadvantage :**
In Protection mode, client application may receive operation-key with a delay.

**Proposals :**
Can we modify the description of the Protection mode mentioned in the [comment](https://github.com/openBackhaul/OperationKeyManagement/issues/39#issue-1354033930) to include functionality to immediately update the operation-key after got notified by /v1/regard-updated-link, 

**Proposal#1 :** 
```
protection: a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link) and new values get periodically written into the operationKey attributes at servers and connected clients.
```

**Proposal#2 :** 
```
protection: a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link) and gets periodically updated.
```

**Comment by MartinSunal** [comment]
It's been agreed that "protection" mode can work as "reaction" + updating keys in cycles.

There are two more things to discuss:
1. What should /v1/regard-updated-link do and return when mode is "off"?
2. When mode "off" is going to be enabled, should there be any other logic executed besides stopping of sending cyclic update (when we go from "protection" to "off")?

**Comment by openBackhaul** [comment]
**Updated Proposal for changes to the OAS:**

- The value 'string-profile-1-0:STRING_VALUE_TYPE_SANITATION' shall be deleted from the modeling, since necessary data is no longer provided by the ApplicationLayerTopology application.  
 
- The following description shall be added to the PUT method for setting the value of the String:
```
description: >
  'reactive: A new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link).
   protection: A new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link) and this value gets periodically changed afterwards.
   off: The application assures open interfaces by periodically writing the default value into the operationKey attributes at servers and clients.
  '
```

**Comment by IswaryaaS** [comment]
The descriptions needs to be added to putStringProfileStringValue

**Comment by openBackhaul** [comment]
The description shall be updated for the REACTIVE mode from 
"reactive: A new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link))"
to
"reactive: After an initial walk through, a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link))"

**Comment by openBackhaul** [comment]
Following comment added:
```
description: >
  'reactive: After initially updating the keys at all servers and clients, a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link))
  protection: A new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link) and this value gets periodically changed afterwards.
  off: The default value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link) and periodically again afterwards.'
```
