### ISSUE TITLE
server: /v1/start-application-in-generic-representation : add display-browser-in-new-window attribute to response-body

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#41]
According to the schema of /v1/start-application-in-generic-representation, consequent-action-list has an attribute called display-in-new-browser-window which is missing in the response-body current implementation. This needs to be added.

**Comment by MartinSunal** [comment]
"display-in-new-browser-window" is not in current version of OAS.
Closing it now and it can be reopened after OAS file is updated.
