### ISSUE TITLE
server : /v1/list-applications to be updated for all http and tcp-clients in logical-termination-point list

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#43]
Currently, the service /v1/list-applications responds with only the data of external applications (picked from OUTPUT fc-port of CyclicOperationCausesOperationKeyUpdates forwarding-construct).
The list in response-body could be directly retrieved  from the list of http-client(s) and it's corresponding tcp-client(s) present in logical-termination-point. (This might include some additional data of OldRelease and NewRelease)

**Comment by MartinSunal** [comment]
Description of /v1/list-applications says: 'Provides list of applications that are receiving operationKeys'

IMO, it is list of apps in CyclicOperationCausesOperationKeyUpdates forwarding-construct.

Let me know if it needs to be changed anyway.

**Comment by IswaryaaS** [comment]
Agree with clarification, hence closing the issue.
