### ISSUE TITLE
OAS : /v1/bequeath-your-data-and-die : callback PromptForBequeathingDataCausesALTbeingRequestedToStopNotificationsToOldRelease can be removed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#44]
For /v1/bequeath-your-data-and-die, we have callback PromptForBequeathingDataCausesALTbeingRequestedToStopNotificationsToOldRelease to end notification subscription /v1/notify-link-updates of old OKM. 

Problem statement:
As per issues [#59](https://github.com/openBackhaul/ApplicationLayerTopology/issues/59) and [#79](https://github.com/openBackhaul/ApplicationLayerTopology/issues/79), the forwarding-construct "LinkChangeNotification" could be an INVARIANT_PROCESS_SNIPPET for the subscription /v1/notify-link-updates , where the new subscription overwrites the OUTPUT fc-port of old subscription. 
If so, while sending the callback, PromptForBequeathingDataCausesALTbeingRequestedToNotifyLinkUpdatesToNewRelease, the old-release subscription would be automatically replaced by the new one and an additional callback (PromptForBequeathingDataCausesALTbeingRequestedToStopNotificationsToOldRelease ) would not be required to end the previous subscription.

Proposal:
Can we remove PromptForBequeathingDataCausesALTbeingRequestedToStopNotificationsToOldRelease from the callbacks list of /v1/bequeath-your-data-and-die.

**Comment by openBackhaul** [comment]
Change in underlying conditions:
- In [ApplicationLayerTopology issue#59](https://github.com/openBackhaul/ApplicationLayerTopology/issues/59), it has been decided, NOT to change from subscription to invariant process snipped (=> several applications are allowed to subscribe for notifications about link updates).

Assumed consequences:
- _PromptForBequeathingDataCausesALTbeingRequestedToNotifyLinkUpdatesToNewRelease_ adds a new subscription, but doesn't overwrite the existing subscription of the old release.
- The subscription of the old release must still be deleted, and we continue to need the callback _PromptForBequeathingDataCausesALTbeingRequestedToStopNotificationsToOldRelease_.
- No change would be required.

@IswaryaaS : If you would agree and also see no need for change, please close the issue.

**Comment by IswaryaaS** [comment]
Thanks for clarifying. Hence closing the issue
