### ISSUE TITLE
OAS regard-application callbacks contain implementation details

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/OperationKeyManagement#6]
**Current state:**
Event CyclicOperationCausesOperationKeyUpdates calls these callbacks:
```
ApplicationLayerTopology/v1/list-link-uuids
ApplicationLayerTopology/v1/list-end-points-of-link
ApplicationLayerTopology/v1/provide-current-operation-key
*/v1/update-operation-key
```

Event LinkUpdateNotificationCausesOperationKeyUpdates calls these callbacks:
```
ApplicationLayerTopology/v1/list-end-points-of-link
ApplicationLayerTopology/v1/provide-current-operation-key
*/v1/update-operation-key
```

**Issue:**
```
ApplicationLayerTopology/v1/list-link-uuids
ApplicationLayerTopology/v1/list-end-points-of-link
ApplicationLayerTopology/v1/provide-current-operation-key
```
are just implementation details telling us from where we get information about links and endpoints but they are not actually a callback. The callback is only `*/v1/update-operation-key`. 

**Solution proposal:**
I would remove them from OAS to make API clean and implementation agnostic.

Also in load file, FC CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates should not contain FC-ports which are not callbacks. I would remove them from there as well.

**Comment by MartinSunal** [comment]
The callback in events is actually an operation from regard-application body proposed in #5

**Comment by PrathibaJee** [comment]
>  FC-ports under FC CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates is duplicate and it is never used by OKM application

I can understand the reason behind this statement. I am explaining my understanding in detail here , @MartinSunal , Kindly please correct me if I am is wrong.

1.  In our application pattern , most of the forwardings are "fire and forgot" as the requirement of those request doesn’t need to wait for the response to process something (example : record-service-request to EATL).
2. But in case of the OKM , to update the operation-keys , we have a forwarding construct that consists of a sequence of requests that needs to be performed prior initiating a final request(update-operation-key). 
3. For this , we have the forwarding-construct "CyclicOperationCausesOperationKeyUpdates" , 
      * first two output fc-ports are to gather information about the client and server uuids , 
      /v1/list-link-uuids
      /v1/list-end-points-of-link
      * third output fc-port is to set the operation key , 
      /v1/update-operation-key
4. In the code , we are not using the ApplicationPattern forwarding functionalities as that doesn’t suit this requirement and using another logic that 
      * &darr;&rarr; fetches the response of /v1/list-link-uuids 
            *  &darr;&rarr; and then fetches the /v1/list-end-points-of-link 
                  *  &darr;&rarr; and then update the operation key.

5. And to do so , we are hardcoding the uuids directly in the code to get the operation-names. 

I hope this is the reason for your statement.

## Proposals :
Further , I have the following proposals to resolve this hardcoding problem and to use forwarding constructs instead , 

Proposal#1 : (No change to load file , implementation change required)
We can use some alternate logics ,
1. From the CyclicOperationCausesOperationKeyUpdates , output fc-ports shall be filtered
2. Order the fc-ports in ascending order based on the local-id
3. index[0] will represent /v1/list-link-uuids , index[1] will represent /v1/list-end-points-of-link

Proposal#2 : (Change required in config file, OAS and server)
1. output fc-port that represents /v1/list-link-uuids , /v1/list-end-points-of-link shall be removed from CyclicOperationCausesOperationKeyUpdates
2. Two new Invariant forwardingConstructs shall be included , 
      - one for /v1/list-link-uuids 
      - one for /v1/list-end-points-of-link 
3. Including sequence of this forwarding in the OAS
4. Modifying the existing logic to not use the hardcoded uuids and point to the new forwardingConstruct to get the mapped operationNames

**Comment by openBackhaul** [comment]
Many thanks for analyzing, clarifying and proposing.

Commenting Proposal#1: 
We just discussed interpreting UUIDs. 
Basing sequence on value of LocalID would be very similar.
Smells fishy.

Commenting Proposal#2:
Seems to be the right way.
Putting FCs (instead of FcPorts) into a sequence is practice in other cases, too (e.g. _/v1/bequeath-your-data-and-die_)
Will try changing the specification accordingly in v2.0.0_spec already.

**Comment by openBackhaul** [comment]
Former _LinkUpdateNotificationCausesOperationKeyUpdates_ FC will be decomposed into FCs:
- _LinkUpdateNotificationCausesRequestForLinkEndPoints_
- _LinkUpdateNotificationCausesOperationKeyUpdates_

Former _CyclicOperationCausesOperationKeyUpdates_ FC will be decomposed into FCs:
- _CyclicOperationCausesRequestForListOfLinks_
- _CyclicOperationCausesRequestForLinkEndPoints_
- _CyclicOperationCausesOperationKeyUpdates_

Problem:
While decomposing, it became obvious that there are no management-requests for the following FCs:
- _LinkUpdateNotificationCausesRequestForLinkEndPoints_
- _CyclicOperationCausesRequestForListOfLinks_
- _CyclicOperationCausesRequestForLinkEndPoints_

In contrary to other communications between the applications of the TAC, OKM addressing _/v1/list-link-uuids_ and _/v1/list-end-points-of-link_ at ALT is not managed by dedicated process, but only by conventional _/v1/update-client_ and _/v1/update-operation-client_.

Consequently, it is unclear where to allocate the callbacks of aforementioned FCs in the OAS.

**Comment by openBackhaul** [comment]
FCs, respectively callbacks, have been created as described above.
[OKM issue#141](https://github.com/openBackhaul/OperationKeyManagement/issues/141) has been created for complementing the missing management requests in v3.0.0_spec.
