### ISSUE TITLE
Basic services

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/OperationKeyManagement#64]
Some OperationClients have to be changed from "basic management" to "basic services":
- ExecutionAndTraceLog://v1/record-service-request
- OamLog://v1/record-oam-request
- AdministratorAdministration://v1/approve-oam-request

**Required changes in ServiceList:**
- move three OperationClients from own-oam::basic to service::basic
- change uuids from e.g. tar-1-0-0-op-c-0040 to tar-1-0-0-op-c-bs-eatl-1-0-0-000 (make off-line table of changes!)

**Required changes in ForwardingList:**
- update uuids (by CTRL+h)

**Required changes in CONFIGfile:**
- move OperationClients
- update uuids of OperationClient (by CTRL+h) according to table
- update uuids of HttpClient and TcpClient

**Required changes in OAS:**
- update uuids of OperationClients, HttpClients and TcpClients (by CTRL+h) according to table

**Comment by kmohr-soprasteria** [comment]
PR #68 already covers the uuid changes from above.  
The ordering of uuids inside serviceList and configFile are different:  
 
![vergleich](https://user-images.githubusercontent.com/57349523/203560079-3f8d860f-f2fd-453a-bf2a-4891a504be2b.jpg)

**Comment by openBackhaul** [comment]
No change required.
