### ISSUE TITLE
Update UUIDs of Services

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/OperationKeyManagement#67]

**Comment by kmohr-soprasteria** [comment]
mapping table:
[mappings.txt](https://github.com/openBackhaul/OperationKeyManagement/files/10032913/mappings.txt)

no changes required for forwarding file

**Comment by openBackhaul** [comment]
has been covered by [pull-request #68](https://github.com/openBackhaul/OperationKeyManagement/pull/68)
