### ISSUE TITLE
/v1/disregard-application should remove the associated fcPorts 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#74]
When a application is disregarded from OperationKeyManagement , then that "'Application will no longer receive operationKeys'".
Currently , disregard-application is removing the operationClient entries , whereas , the associated fcPorts are not removed from the forwardingConstruct CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates.

**Comment by MartinSunal** [comment]
Hi Prathiba,

could you kindly share steps to reproduce? I tried to:

-  add non-existing application 'foo' using /v1/regard-application (which correctly created fc-ports) and then remove it using /v1/disregard-application and everything, including fc-ports was removed correctly

- call /v1/disregard-application on existing application = OamLog, this call did not remove any fc-ports, but there were none associated with forwardingConstructs CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates

- call /v1/disregard-application on existing application = TypeApprovalRegistry, this call did remove also fc-ports

Thanks,
Martin

**Comment by PrathibaJee** [comment]
Martin , thanks for checking on the scenarios. 
This issue is reproducible when the associated http-client has more than one operation-client. 
For example , 
- RegistryOffice version 0.0.1 has 8 operation-clients associated to the http-client and while trying to disregard this application , only the operation-client gets removed from the logical-termination-point. 
- But the fc-ports in the forwarding-construct LinkUpdateNotificationCausesOperationKeyUpdates , CyclicOperationCausesOperationKeyUpdates are still available for the deleted operation-clients.

**Comment by PrathibaJee** [comment]
Martin , following is the scenario that was tested , 
**Scenario 1 : (Brand new application)**
1. Regard a new application "NewApplication", "1.0.0". 
2. Result : This creates 
    -  a tcp-client , http-client and an operation-client(v1/update-operation-key)
    -  fc-port in the FCs CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates
3. disregard the application "NewApplication", "1.0.0". 
4. Result : Code is removing ,
    - tcp-client , http-client and an operation-client(v1/update-operation-key) 
    - fc-port in the FCs CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates

**Scenario 2 : (Registry Office)**
1. Since this is an already approved application , we can able to see the tcp,http client and 8 operation-clients which consists of v1/update-operation-key as well as other clients like(deregister-application, register-application etc.,)
2. disregard the application "RegistryOffice", "1.0.0". 
3. Result : Code is removing ,
    - operation-client v1/update-operation-key 
    **Problem :** It's not removing the fc-port in the FCs CyclicOperationCausesOperationKeyUpdates, LinkUpdateNotificationCausesOperationKeyUpdates

Also kindly please let me whether we can have a call to look into the scenario
