### ISSUE TITLE
Updating the UUIDs of FCs

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/OperationKeyManagement#76]
Process for updating the UUIDs of FCs

- [x] Katharina to update fc-uuid in CONFIGfile and OAS wherever applicable referencing from ForwardingList on feature branch
- [x] Katharina to create pull request from feature branch
- [ ] Iswaryaa to review the pull request
If no errors found
- [ ] Iswaryaa to Approve the pull request
- [ ] Iswaryaa to merge feature branch to develop
- [ ] Iswaryaa to delete feature branch and close this issue

**Comment by kmohr-soprasteria** [comment]
Mappings for config file from forwardings list:
![mapping_okm](https://user-images.githubusercontent.com/57349523/203314542-f795f82d-e901-4166-946c-ef0a2aa0db6e.png)

Due to new forwarding in forwardingList with uuid okm-1-0-0-op-fc-bm-005, there is an offset in the mapping table.
