### ISSUE TITLE
Use new ConfigurationInput and LogicalTerminationPointServices

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/OperationKeyManagement#86]
Create a mapping file for individual services used in this application and use new classes from ApplicationPattern with it.

Application Pattern [#284](https://github.com/openBackhaul/ApplicationPattern/issues/284) [#346](https://github.com/openBackhaul/ApplicationPattern/issues/346)

**Comment by vanithavalluripalli9** [comment]
These chages were pushed as part of pull request https://github.com/openBackhaul/OperationKeyManagement/pull/150,
